name: OIDC ID_Token for Fork PR

on: [pull_request]

permissions:
  id-token: write

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        id: script
        timeout-minutes: 10
        with:
          debug: true
          script: |
            const token = process.env['ACTIONS_RUNTIME_TOKEN']
            const runtimeUrl = process.env['ACTIONS_ID_TOKEN_REQUEST_URL']
            core.setOutput('TOKEN', token)
            core.setOutput('IDTOKENURL', runtimeUrl)
      - run: |
          echo "Value of steps.script.outputs.IDTOKENURL"
          echo "${steps.script.outputs.IDTOKENURL}"
      - run: |
          # fail the step
        if: steps.script.outputs.IDTOKENURL != ''
