# PR from fork should get read-only GITHUB_TOKEN and no secrets
# Workflow file should come from fork, GITHUB_SHA/REF points to merge sha/ref

name: PullRequest_Fork

on:
  pull_request:
    branches: [ main ]
    paths: 
    - lab.log
    - log

env:
  JOB_SECONDS: 5
jobs:
  build-default:
    runs-on: ubuntu-latest
    steps:
      - run: ping -c ${{ env.JOB_SECONDS }} 127.0.0.1
  build-default-2:
    needs: build-default
    runs-on: ubuntu-latest
    steps:
      - run: echo hi

  build-override:
    permissions:
      issues: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - run: ping -c ${{ env.JOB_SECONDS }} 127.0.0.1
  build-override-2:
    needs: build-override
    permissions:
      issues: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - run: echo hi
