
name: Delete Labels

on:
  workflow_dispatch:
  push:
    paths: '.github/workflows/delete_labels.yml'
  schedule:
    - cron: '0 */1 * * *'

permissions: write-all

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/github-script@v7
      with:
        script: |
          const owner = context.repo.owner;
          const repo = context.repo.repo;

          // List workflow runs
          const runs = await github.rest.actions.listWorkflowRunsForRepo({
            owner,
            repo,
            per_page: 1,
            status: 'completed'
          });

          if (runs.data.workflow_runs.length > 0) {
            const latestRun = runs.data.workflow_runs[0];
            console.log(`Latest workflow run ID: ${latestRun.id}`);
          } else {
            console.log('No workflow runs found.');
            return;
          }

          for await (const response of github.paginate.iterator(
            github.rest.issues.listLabelsForRepo,
            { owner, repo }
          )) {
            for (const label of response.data) {
              try {
                await github.rest.issues.deleteLabel({
                  owner,
                  repo,
                  name: label.name
                });
                console.log(`Deleted label: ${label.name}`);
              } catch (error) {
                console.log(`Failed to delete label: ${label.name}, error: ${error}`);
              }
            }
          }
