# Pull_request_target from fork should get read-only GITHUB_TOKEN and no secrets
# Workflow file should not come from fork, GITHUB_SHA/REF points to base repo target

name: PullRequestTarget_Fork

on:
  pull_request_target:
    branches: [ master ]

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: nosuch/nosuch@bad
